; flb_runner 参数记忆(确定参数窗口时自动更新, 可删除)
[模板]
template = 0

[通用]
offset_dist = 35.0000
hole_dist = 50.0000
hole_extend = 15.0000
fillet_r = 15.0000
fillet_r_hole = 15.0000
chamfer_d = 5.0000
screw_in = 10.0000
screw_r = 4.2500
nozzle_offset = 40.0000
nozzle_r = 11.3500
pin_r = 3.0000
zjj_r = 14.3500

[矩形]
rect_chamfer = 10.0000
pin_r = 3.0000
nozzle_r = 11.3500
screw_r = 4.2500
screw_in = 15.0000
fillet_r_hole = 15.0000
hole_dist = 50.0000
offset_dist = 35.0000

[假体]
envelope = 0

