; jrt_runner 参数记忆(确定参数窗口时自动更新, 可删除)
[模板]
template = 1

[通用二]
jrt2_half_w = 16.5000
jrt2_end_r = 12.0000
jrt_inner_step = 4.0000
jrt_inner_count = 2.0000
jrt2_neck_len = 65.0000
jrt2_neck_off = 35.0000
jrt2_close_r = 15.0000
jrt2_trim_r = 15.0000

[通用一]
jrt_inner_count = 0.0000
jrt_inner_step = 4.0000
jrt_cap_r = 29.0000
jrt_fillet_r = 19.0000
jrt_cap_inset = 11.0000
jrt_offset = 29.0000

